USE SCHEMA DEMO.AFS_POC;

CREATE OR REPLACE TABLE DEMO.AFS_POC.INDIVIDUAL_DEMOGRAPHIC_SPINE (
  afs_individual_id VARCHAR COMMENT 'Individual id',
  city_plac VARCHAR(28) COMMENT 'City Name',
  city_cnab VARCHAR(13) COMMENT 'City Name - Abbreviated',
  stat_abbr VARCHAR(2) COMMENT 'State Abbreviation',
  recd_zipc VARCHAR(5) COMMENT 'ZIP Code',
  post_zip4 VARCHAR(4) COMMENT 'ZIP+4',
  geoc_stat_2000 VARCHAR(2) COMMENT 'State Code',
  geoc_cnty_2000 VARCHAR(3) COMMENT 'County Code',
  geoc_blck_2020 VARCHAR(7) COMMENT 'Census 2020: Tract and Block Group',
  geoc_bid_2020 VARCHAR(3) COMMENT 'Census 2020:  Block ID',
  geo_cntyname VARCHAR(25) COMMENT 'County Name',
  geog_levl VARCHAR(1) COMMENT 'Match level for geo data',
  recd_p_id_1 VARCHAR(10) COMMENT 'Person 1: Person Id Number',
  lr_pers_flag_1 VARCHAR(1) COMMENT 'Person 1:  List Rental Qualified',
  perstype_1 VARCHAR(1) COMMENT 'Person 1: Person Type',
  bdat_bdat_1 VARCHAR(6) COMMENT 'Person 1: Birth Year and Month',
  yearofbirth_1 DATE COMMENT 'Person 1: Year of Birth',
  combined_age_1 VARCHAR(3) COMMENT 'Person 1: Combined Age',
  person__age_range_1924 VARCHAR(1) COMMENT 'Person 1: Age Range 19-24',
  person__age_range_2529 VARCHAR(1) COMMENT 'Person 1: Age Range 25-29',
  person__age_range_3034 VARCHAR(1) COMMENT 'Person 1: Age Range 30-34',
  person__age_range_3539 VARCHAR(1) COMMENT 'Person 1: Age Range 35-39',
  person__age_range_4044 VARCHAR(1) COMMENT 'Person 1: Age Range 40-44',
  person__age_range_4549 VARCHAR(1) COMMENT 'Person 1: Age Range 45-49',
  person__age_range_5054 VARCHAR(1) COMMENT 'Person 1: Age Range 50-54',
  person__age_range_5559 VARCHAR(1) COMMENT 'Person 1: Age Range 55-59',
  person__age_range_adults_25__54 VARCHAR(1) COMMENT 'Person 1: Age Range Adults 25 - 54',
  person__age_range_adults_25 VARCHAR(1) COMMENT 'Person 1: Age Range Adults 25+',
  person__agegender_female_25__54 VARCHAR(1) COMMENT 'Person 1: Age/Gender Female 25 - 54',
  person__agegender_female_25 VARCHAR(1) COMMENT 'Person 1: Age/Gender Female 25+',
  person__agegender_male_25__54 VARCHAR(1) COMMENT 'Person 1: Age/Gender Male 25 - 54',
  person__agegender_male_25 VARCHAR(1) COMMENT 'Person 1: Age/Gender Male 25+',
  gndr_gndr_1 VARCHAR(1) COMMENT 'Person 1: Gender',
  mrtl_model_1 VARCHAR(2) COMMENT 'Person 1: Marital Status',
  ocup_ocup_1 VARCHAR(2) COMMENT 'Person 1: Occupation Code',
  ocup_model_v2_1 VARCHAR(2) COMMENT 'Person 1: Occupation Group V2',
  educ_model_1 VARCHAR(2) COMMENT 'Person 1: Education Model',
  educ_levl_1 VARCHAR(1) COMMENT 'Person 1: Education Level',
  biz_owner_1 VARCHAR(1) COMMENT 'Person 1: Business Owner',
  et_cntry_1 VARCHAR(2) COMMENT 'Person 1: Ethnic - Country Of Origin',
  et_code_1 VARCHAR(2) COMMENT 'Person 1: Ethnic - Ethnic',
  et_grp_1 VARCHAR(1) COMMENT 'Person 1: Ethnic - Group',
  et_lang_1 VARCHAR(2) COMMENT 'Person 1: Ethnic - Language Preference',
  et_relg_1 VARCHAR(1) COMMENT 'Person 1: Ethnic - Religion',
  health_well_being_1 VARCHAR(1) COMMENT 'Person 1: Health and Well Being',
  mobileusers_1 VARCHAR(1) COMMENT 'Person 1: Mobile Users',
  political_code_1 VARCHAR(2) COMMENT 'Person 1: Political Affiliation',
  political_personas_1 VARCHAR(2) COMMENT 'Person 1: PoliticalPersona I1',
  retail_shopper_1 VARCHAR(1) COMMENT 'Person 1: Retail Shopper',
  technology_adoption_1 VARCHAR(1) COMMENT 'Person 1: Technology Adoption',
  con20_age_65_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Age 65+',
  con20_financial_advice_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Financial Advice',
  con20_occ_social_svc_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Occ Social Services',
  con20_occ_education_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Occ Education',
  con20_occ_small_biz_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Occ Small Biz Owner',
  con20_occ_work_home_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Occ Essential Worker',
  con20_occ_construction_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Occ Construction',
  con20_occ_government_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Occ Government',
  con20_occ_retail_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Occ Retail',
  con20_occ_qsr_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Occ QSR Restaurant',
  con20_occ_travel_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Occ Travel Industry',
  con20_fam_younger_kids_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Family Younger Kids',
  con20_fam_older_kids_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Fam Older Kids',
  con20_bus_travelers_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Business Travelers',
  con20_retiredempty_nest_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Retired/Empty Nest',
  con20_single_adults_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Single Adults',
  con20_generation_z_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Generation Z',
  con20_gen_millennials_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Generation Millennials',
  con20_gen_x_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Generation X',
  con20_gen_boomers_1 VARCHAR(1) COMMENT 'Person 1: Cons Behavior Generation Boomers',
  dad_crafty_1 VARCHAR(1) COMMENT 'Person 1: Dads Crafty',
  dad_fitness_1 VARCHAR(1) COMMENT 'Person 1: Dads Fitness',
  dad_garden_1 VARCHAR(1) COMMENT 'Person 1: Dads Gardening',
  dad_stayhome_1 VARCHAR(1) COMMENT 'Person 1: Dads Stay at home',
  dad_working_1 VARCHAR(1) COMMENT 'Person 1: Dads Working',
  dad_boomer_1 VARCHAR(1) COMMENT 'Person 1: Dads Baby Boomer',
  dad_genx_1 VARCHAR(1) COMMENT 'Person 1: Dads Gen X',
  dad_geny_1 VARCHAR(1) COMMENT 'Person 1: Dads Gen Y',
  dad_married_1 VARCHAR(1) COMMENT 'Person 1: Dads Married',
  dad_single_1 VARCHAR(1) COMMENT 'Person 1: Dads Single',
  dad_1chld_1 VARCHAR(1) COMMENT 'Person 1: Dads only 1 child',
  dad_2child_1 VARCHAR(1) COMMENT 'Person 1: Dads 2+ children',
  dad_0_3yrs_1 VARCHAR,
  dad_4_6yrs_1 VARCHAR,
  dad_tween_1 VARCHAR(1) COMMENT 'Person 1: Dads w tween 7-12yrs',
  dad_teen_1 VARCHAR(1) COMMENT 'Person 1: Dads w teen 13-15yrs',
  dad_highs_1 VARCHAR(1) COMMENT 'Person 1: Dads w highschooler',
  rec_married_date_1 DATE COMMENT 'Person 1: Married - Date',
  rec_married_last12mos_1 VARCHAR(1) COMMENT 'Person 1: Married - Last 12 Mo',
  rec_married_last6mos_1 VARCHAR(1) COMMENT 'Person 1: Married - Last 6 Mos',
  rec_married_last3mos_1 VARCHAR(1) COMMENT 'Person 1: Married - Last 3 Mos',
  person__moms_age_25__54 VARCHAR(1) COMMENT 'Person 1: Moms Age 25 - 54',
  person__moms_age_25 VARCHAR(1) COMMENT 'Person 1: Moms Age 25+',
  mom_crafty_1 VARCHAR(1) COMMENT 'Person 1: Moms Crafty',
  mom_fitness_1 VARCHAR(1) COMMENT 'Person 1: Moms Fitness',
  mom_garden_1 VARCHAR(1) COMMENT 'Person 1: Moms Gardening',
  mom_stayhome_1 VARCHAR(1) COMMENT 'Person 1: Moms Stay at home',
  mom_working_1 VARCHAR(1) COMMENT 'Person 1: Moms Working',
  mom_boomer_1 VARCHAR(1) COMMENT 'Person 1: Moms Baby Boomer',
  mom_genx_1 VARCHAR(1) COMMENT 'Person 1: Moms Gen X',
  mom_geny_1 VARCHAR(1) COMMENT 'Person 1: Moms Gen Y',
  mom_married_1 VARCHAR(1) COMMENT 'Person 1: Moms Married',
  mom_single_1 VARCHAR(1) COMMENT 'Person 1: Moms Single',
  mom_1chld_1 VARCHAR(1) COMMENT 'Person 1: Moms only 1 child',
  mom_2child_1 VARCHAR(1) COMMENT 'Person 1: Moms 2+ children',
  mom_0_3yrs_1 VARCHAR,
  mom_4_6yrs_1 VARCHAR,
  mom_tween_1 VARCHAR(1) COMMENT 'Person 1: Moms w tween 7-12yrs',
  mom_teen_1 VARCHAR(1) COMMENT 'Person 1: Moms with teen 13-15yrs',
  mom_highs_1 VARCHAR(1) COMMENT 'Person 1: Moms w highschooler',
  rec_single_date_1 DATE COMMENT 'Person 1: Single - Date',
  rec_single_last3mos_1 VARCHAR(1) COMMENT 'Person 1: Single - Last 3 Mos',
  rec_single_last6mos_1 VARCHAR(1) COMMENT 'Person 1: Single - Last 6 Mos',
  rec_single_last12mos_1 VARCHAR(1) COMMENT 'Person 1: Single - Last 12 Mos',
  person__baby_boomers_19461964 VARCHAR(1) COMMENT 'Person 1: Baby Boomers (1946-1964)',
  person__baby_boomers_female_194664 VARCHAR(1) COMMENT 'Person 1: Baby Boomers Female (1946-64)',
  person__baby_boomers_male_19461964 VARCHAR(1) COMMENT 'Person 1: Baby Boomers Male (1946-1964)',
  person__gen_x_19651979 VARCHAR(1) COMMENT 'Person 1: Gen X (1965-1979)',
  person__gen_x_female_19651979 VARCHAR(1) COMMENT 'Person 1: Gen X Female (1965-1979)',
  person__gen_x_male_19651979 VARCHAR(1) COMMENT 'Person 1: Gen X Male (1965-1979)',
  person__gen_y_19801993 VARCHAR(1) COMMENT 'Person 1: Gen Y (1980-1993)',
  person__gen_y_female_19801993 VARCHAR(1) COMMENT 'Person 1: Gen Y Female (1980-1993)',
  person__gen_y_male_19801993 VARCHAR(1) COMMENT 'Person 1: Gen Y Male (1980-1993)',
  lr_livu_flag VARCHAR(1) COMMENT 'List Rental Qualified',
  mobj_mobj VARCHAR(1) COMMENT 'Mail Objector',
  aqi VARCHAR(1) COMMENT 'Address Quality Indicator',
  geog_tzon VARCHAR(1) COMMENT 'Time Zone',
  lu_a_adat DATE COMMENT 'Activity Date',
  ncoa_move_update_method_code VARCHAR(1) COMMENT 'NCOA Move Update Code',
  ncoa_move_update_date DATE COMMENT 'NCOA Move Update Date',
  lu_inc_model_v6_amt VARCHAR(3) COMMENT 'Estimated Household Income Amount V6',
  lu_inc_model_v6 VARCHAR(1) COMMENT 'Estimated Household Income Range Code V6',
  county_inc_index VARCHAR(3) COMMENT 'County EHI Index',
  state_inc_index VARCHAR(3) COMMENT 'State EHI Index',
  lu_cntyinc VARCHAR(2) COMMENT 'County EHI Percentile',
  lu_natlinc VARCHAR(2) COMMENT 'Income Percentile - National',
  econ_income_index_ VARCHAR(5) COMMENT 'Economic Income Index',
  echv VARCHAR(7) COMMENT 'Estimated Current Home Value',
  echv_rng VARCHAR(1) COMMENT 'Estimated Current Home Value range',
  cnty_echv_index VARCHAR(3) COMMENT 'County ECHV index',
  cnty_echv_pct VARCHAR(2) COMMENT 'County ECHV percentile',
  combined_homeowner VARCHAR(1) COMMENT 'Homeowner: Combined Homeowner/Renter',
  dwelling_type VARCHAR(1) COMMENT 'Dwelling Type',
  du_size VARCHAR(1) COMMENT 'Dwelling Unit Size',
  lngth_of_res VARCHAR(2) COMMENT 'Length of Residence',
  lngth_of_res_months VARCHAR(2) COMMENT 'Length of Residence in Months',
  zip_zcl VARCHAR(2) COMMENT 'ZIP Locality',
  hbi VARCHAR(1) COMMENT 'Home Business',
  hh_composition_code VARCHAR(1) COMMENT 'Household Composition',
  young_adult_prsnt VARCHAR(1) COMMENT 'Young Adult Present',
  elderly_prsent VARCHAR(1) COMMENT 'Elderly Person Indicator',
  rec_adultcnt VARCHAR(1) COMMENT 'Number of Adults in Living Unit',
  rec_childcnt VARCHAR(1) COMMENT 'Number of Children in Living Unit',
  rec_perscnt VARCHAR(1) COMMENT 'Number of Persons in Living Unit',
  age_range_1924 VARCHAR(1) COMMENT 'Age Range: 19-24',
  age_range_2529 VARCHAR(1) COMMENT 'Age Range: 25-29',
  age_range_3034 VARCHAR(1) COMMENT 'Age Range: 30-34',
  age_range_3539 VARCHAR(1) COMMENT 'Age Range: 35-39',
  age_range_4044 VARCHAR(1) COMMENT 'Age Range: 40-44',
  age_range_4549 VARCHAR(1) COMMENT 'Age Range: 45-49',
  age_range_5054 VARCHAR(1) COMMENT 'Age Range: 50-54',
  age_range_5559 VARCHAR(1) COMMENT 'Age Range: 55-59',
  age_range_adults_25__54 VARCHAR(1) COMMENT 'Age Range: Adults 25 - 54',
  age_range_adults_25 VARCHAR(1) COMMENT 'Age Range: Adults 25+',
  agegender_female_25__54 VARCHAR(1) COMMENT 'Age/Gender: Female 25 - 54',
  agegender_female_25 VARCHAR(1) COMMENT 'Age/Gender: Female 25+',
  agegender_male_25__54 VARCHAR(1) COMMENT 'Age/Gender: Male 25 - 54',
  agegender_male_25 VARCHAR(1) COMMENT 'Age/Gender: Male 25+',
  pocv4_0_3_code VARCHAR(2) COMMENT 'Children: Age 0-3',
  pocv4_4_6_code VARCHAR(2) COMMENT 'Children: Age 4-6',
  pocv4_7_9_code VARCHAR(2) COMMENT 'Children: Age 7-9',
  pocv4_10_12_code VARCHAR(2) COMMENT 'Children: Age 10-12',
  pocv4_13_15_code VARCHAR(2) COMMENT 'Children: Age 13-15',
  pocv4_16_18_code VARCHAR(2) COMMENT 'Children: Age 16-18',
  poc_0_3_gender VARCHAR(1) COMMENT 'Children: Age 0-3 Gender',
  poc_4_6_gender VARCHAR(1) COMMENT 'Children: Age 4-6  Gender',
  poc_7_9_gender VARCHAR(1) COMMENT 'Children: Age 7-9 Gender',
  poc_10_12_gender VARCHAR(1) COMMENT 'Children: Age 10-12 Gender',
  poc_13_15_gender VARCHAR(1) COMMENT 'Children: Age 13-15  Gender',
  poc_16_18_gender VARCHAR(1) COMMENT 'Children: Age 16-18 Gender',
  pocv4_code VARCHAR(2) COMMENT 'Children: Presence of Child 0-18',
  mosaic_hh_v3 VARCHAR(3) COMMENT 'Mosaic Household',
  mosaic_z4_v3 VARCHAR(3) COMMENT 'Mosaic ZIP4',
  ds_key_mosaic_household_group_code VARCHAR(1) COMMENT 'Mosaic Household group code',
  phone_feature_phone VARCHAR(2) COMMENT 'Phone: Feature Phone User',
  phone_heavy_cellular VARCHAR(2) COMMENT 'Phone: Frequent Cellular User',
  metro_flag VARCHAR(1) COMMENT 'CBSA-METRO-FLAG',
  mcd_code VARCHAR(5) COMMENT 'MCD/CCD Code',
  congress_districts_2020 VARCHAR(5) COMMENT 'Congressional Districts 2020',
  rural_urban_cntysz_code VARCHAR(1) COMMENT 'Census: Rural-Urban County Size Code',
  cbsa_type VARCHAR(1) COMMENT 'Core Based Statistical Area Type',
  cbsa_code VARCHAR(5) COMMENT 'Core Based Statistical Areas (CBSA)',
  dad_crafty_hh VARCHAR(1) COMMENT 'Dads: Crafty',
  dad_fitness_hh VARCHAR(1) COMMENT 'Dads: Fitness',
  dad_garden_hh VARCHAR(1) COMMENT 'Dads: Gardening',
  dad_stayhome_hh VARCHAR(1) COMMENT 'Dads: Stay at home',
  dad_boomer_hh VARCHAR(1) COMMENT 'Dads: Baby Boomer (1946-1964)',
  dad_genx_hh VARCHAR(1) COMMENT 'Dads: Gen X (1965-1979)',
  dad_geny_hh VARCHAR(1) COMMENT 'Dads: Gen Y (1980-1993)',
  dad_married_hh VARCHAR(1) COMMENT 'Dads: Married',
  dad_single_hh VARCHAR(1) COMMENT 'Dads: Single',
  dad_1chld_hh VARCHAR(1) COMMENT 'Dads: only 1 child',
  dad_2child_hh VARCHAR(1) COMMENT 'Dads: 2+ children',
  dad_0 VARCHAR,
  dad_4 VARCHAR,
  dad_tween_hh VARCHAR(1) COMMENT 'Dads: with tween 7-12yrs',
  dad_teen_hh VARCHAR(1) COMMENT 'Dads: with teen 13-15yrs',
  dad_highs_hh VARCHAR(1) COMMENT 'Dads: with highschool 16-18yrs',
  dad_working_hh VARCHAR(1) COMMENT 'Dads: Working',
  moms_age_25__54 VARCHAR(1) COMMENT 'Moms: Age 25 - 54',
  moms_age_25 VARCHAR(1) COMMENT 'Moms: Age 25+',
  mom_crafty_hh VARCHAR(1) COMMENT 'Moms: Crafty',
  mom_fitness_hh VARCHAR(1) COMMENT 'Moms: Fitness',
  mom_garden_hh VARCHAR(1) COMMENT 'Moms: Gardening',
  mom_stayhome_hh VARCHAR(1) COMMENT 'Moms: Stay at home',
  mom_boomer_hh VARCHAR(1) COMMENT 'Moms: Baby Boomer (1946-1964)',
  mom_genx_hh VARCHAR(1) COMMENT 'Moms: Gen X (1965-1979)',
  mom_geny_hh VARCHAR(1) COMMENT 'Moms: Gen Y (1980-1993)',
  mom_married_hh VARCHAR(1) COMMENT 'Moms: Married',
  mom_single_hh VARCHAR(1) COMMENT 'Moms: Single',
  mom_1chld_hh VARCHAR(1) COMMENT 'Moms: only 1 child',
  mom_2child_hh VARCHAR(1) COMMENT 'Moms: 2+ children',
  mom_0_3yrs_hh VARCHAR,
  mom_4_6yrs_hh VARCHAR,
  mom_tween_hh VARCHAR(1) COMMENT 'Moms: with tween 7-12yrs',
  mom_teen_hh VARCHAR(1) COMMENT 'Moms: with teen 13-15yrs',
  mom_highs_hh VARCHAR(1) COMMENT 'Moms: with highschool 16-18yrs',
  mom_working_hh VARCHAR(1) COMMENT 'Moms: Working',
  dm_recently_married_last_3_months VARCHAR,
  dm_recently_married_last_6_months VARCHAR,
  dm_recently_married_last_12_months VARCHAR,
  dm_recently_single_last_3_months VARCHAR,
  dm_recently_single_last_6_months VARCHAR,
  dm_recently_single_last_12_months VARCHAR,
  baby_boomers_19461964 VARCHAR(1) COMMENT 'Baby Boomers (1946-1964)',
  baby_boomers_female_194664 VARCHAR(1) COMMENT 'Baby Boomers Female (1946-64)',
  baby_boomers_male_19461964 VARCHAR(1) COMMENT 'Baby Boomers Male (1946-1964)',
  gen_x_19651979 VARCHAR(1) COMMENT 'Gen X (1965-1979)',
  gen_x_female_19651979 VARCHAR(1) COMMENT 'Gen X Female (1965-1979)',
  gen_x_male_19651979 VARCHAR(1) COMMENT 'Gen X Male (1965-1979)',
  gen_y_19801993 VARCHAR(1) COMMENT 'Gen Y (1980-1993)',
  gen_y_female_19801993 VARCHAR(1) COMMENT 'Gen Y Female (1980-1993)',
  gen_y_male_19801993 VARCHAR(1) COMMENT 'Gen Y Male (1980-1993)',
  digital_dads VARCHAR(1) COMMENT 'Digital Dads',
  digital_moms VARCHAR(1) COMMENT 'Digital Moms',
  working_couples VARCHAR(1) COMMENT 'Working Couples (Dual Income)',
  waistband_models VARCHAR(1) COMMENT 'Waistband Models',
  green_aware VARCHAR(1) COMMENT 'Green Aware',
  greenaware_tiers VARCHAR(2) COMMENT 'GreenAware Tiers',
  rchr_bdat DATE COMMENT 'Property/Realty: Home Year Built',
  rsiz_stor VARCHAR(3) COMMENT 'Property/Realty: Home Stories',
  rsiz_bthr VARCHAR(3) COMMENT 'Property/Realty: Home Bath',
  rsiz_bedr VARCHAR(2) COMMENT 'Property/Realty: Home Bedrooms',
  rchr_swim VARCHAR(1) COMMENT 'Property/Realty: Home Swimming Pool Indicator',
  rsiz_totr VARCHAR(2) COMMENT 'Property/Realty: Home Total Rooms',
  rchr_extw VARCHAR(2) COMMENT 'Property/Realty: Home Exterior Wall Type',
  rchr_heat VARCHAR(1) COMMENT 'Property/Realty: Home Heat Indicator',
  rchr_frpl VARCHAR(1) COMMENT 'Property/Realty: Home Fireplaces',
  rchr_airc VARCHAR(1) COMMENT 'Property/Realty: Home Air Conditioning',
  rchr_flrc VARCHAR(1) COMMENT 'Property/Realty: Home Floor Cover Indicator',
  rsiz_prop VARCHAR(2) COMMENT 'Property/Realty: Property Indicator',
  rchr_bldc VARCHAR(2) COMMENT 'Property/Realty: Building construction indicator',
  year_built DATE COMMENT 'Property/Realty: Year Built',
  year_built_conf VARCHAR(1) COMMENT 'Property/Realty: Year Built Confidence',
  rval_totl VARCHAR(4) COMMENT 'Property/Realty: Home Total Value',
  rval_totl_rng VARCHAR(1) COMMENT 'Property/Realty: Total value ranges',
  rval_impr VARCHAR(4) COMMENT 'Property/Realty: Home Improvement Value',
  rval_impr_rng VARCHAR(1) COMMENT 'Property/Realty: Improvement value ranges',
  rval_tax_ VARCHAR(4) COMMENT 'Property/Realty: Total Tax',
  rval_tax_rng_ VARCHAR(1) COMMENT 'Property/Realty: Tax payment ranges',
  rval_land VARCHAR(4) COMMENT 'Property/Realty: Home Land Value',
  rval_land_rng VARCHAR(1) COMMENT 'Property/Realty: Land value ranges',
  rsiz_lasf VARCHAR(4) COMMENT 'Property/Realty: Home Land Square Footage',
  rsiz_lasf_rng VARCHAR(1) COMMENT 'Property/Realty: Land square footage ranges',
  rsiz_busf VARCHAR(3) COMMENT 'Property/Realty: Home Building Square Footage',
  rsiz_busf_rng VARCHAR(1) COMMENT 'Property/Realty: Building square footage ranges',
  rsiz_basf VARCHAR(3) COMMENT 'Property/Realty: Home Base Square Footage',
  rsiz_basf_rng VARCHAR(1) COMMENT 'Property/Realty: Base square footage ranges',
  rsiz_ladf VARCHAR(4) COMMENT 'Property/Realty: Home Land Depth Footage',
  rsiz_ladf_rng VARCHAR(1) COMMENT 'Property/Realty: Land depth footage ranges',
  rsiz_laff VARCHAR(4) COMMENT 'Property/Realty: Home Land Front Footage',
  rchr_acres VARCHAR(6) COMMENT 'Property/Realty: Land acres',
  rsiz_laff_rng VARCHAR(1) COMMENT 'Property/Realty: Land front footage ranges',
  rchr_acres_rng VARCHAR(1) COMMENT 'Property/Realty: Land acres ranges',
  mult_realty_flag VARCHAR(1) COMMENT 'Investment Property: Additional investment flag',
  city_plac_i1 VARCHAR(28) COMMENT 'Investment Property: City name',
  county_code_i1 VARCHAR(3) COMMENT 'Investment Property: County Code',
  deed_date_i1 DATE COMMENT 'Investment Property: Date of Warranty deed',
  eqty_deed_i1 DATE COMMENT 'Investment Property: Deed date of Equity Loan',
  refi_deed_i1 DATE COMMENT 'Investment Property: Deed date of Refinance Loan',
  eqty_amnt_i1 VARCHAR(4) COMMENT 'Investment Property: Equity Amount',
  eqty_amnt_i1_rng VARCHAR(1) COMMENT 'Investment Property: Equity amount ranges',
  eqty_lndr_i1898 VARCHAR,
  eqty_lndr_i1899 VARCHAR,
  eqty_ttype_i1 VARCHAR(1) COMMENT 'Investment Property: Equity Loan Type',
  eqty_rtyp_i1 VARCHAR(1) COMMENT 'Investment Property: Equity Rate Type',
  eqty_term_i1 VARCHAR(4) COMMENT 'Investment Property: Equity Term',
  mort_amnt_i1 VARCHAR(4) COMMENT 'Investment Property: Mortgage amount',
  mort_amnt_i1_rng VARCHAR(1) COMMENT 'Investment Property: Mortgage amount ranges',
  mort_lndr_i1905 VARCHAR,
  mort_lndr_i1906 VARCHAR,
  mort_ttype_i1 VARCHAR(1) COMMENT 'Investment Property: Mortgage Loan Type',
  mort_rtyp_i1 VARCHAR(1) COMMENT 'Investment Property: Mortgage Rate Type',
  mort_term_i1 VARCHAR(4) COMMENT 'Investment Property: Mortgage Term',
  prmy_numb_i1 VARCHAR(10) COMMENT 'Investment Property: Primary (house) number',
  prch_amnt_i1 VARCHAR(4) COMMENT 'Investment Property: Purchase Amount',
  prch_amnt_i1_rng VARCHAR(1) COMMENT 'Investment Property: Purchase amount ranges',
  refi_amnt_i1 VARCHAR(4) COMMENT 'Investment Property: Refinance Amount in thousands',
  refi_amnt_i1_rng VARCHAR(1) COMMENT 'Investment Property: Refinance Amount Ranges',
  refi_lndr_i1915 VARCHAR,
  refi_lndr_i1916 VARCHAR,
  refi_rplc_i1 DATE COMMENT 'Investment Property: Refinance date on file',
  refi_ttype_i1 VARCHAR(1) COMMENT 'Investment Property: Refinance Loan Type',
  refi_rtyp_i1 VARCHAR(1) COMMENT 'Investment Property: Refinance Rate Type',
  refi_term_i1 VARCHAR(4) COMMENT 'Investment Property: Refinance term',
  scdy_numb_i1 VARCHAR(8) COMMENT 'Investment Property: Secondary number (e.g. apt #)',
  scdy_desg_i1 VARCHAR(6) COMMENT 'Investment Property: Secondary unit designator',
  state_abbr_i1 VARCHAR(2) COMMENT 'Investment Property: State Abbreviation',
  state_i1 VARCHAR(2) COMMENT 'Investment Property: State Code',
  strt_name_i1 VARCHAR(28) COMMENT 'Investment Property: Street name',
  strt_post_i1 VARCHAR(2) COMMENT 'Investment Property: Street post-directional',
  strt_pred_i1 VARCHAR(2) COMMENT 'Investment Property: Street pre-directional',
  strt_sufx_i1 VARCHAR(4) COMMENT 'Investment Property: Street suffix',
  invs_type_i1 VARCHAR(1) COMMENT 'Investment Property: Type of investment',
  prch_type_i1 VARCHAR(1) COMMENT 'Investment Property: Type of Purchase',
  recd_zipc_i1 VARCHAR(5) COMMENT 'Investment Property: ZIP Code',
  tod_model VARCHAR(2) COMMENT 'TrueTouch: Time of Day model',
  act_int_amusement_park_visitors VARCHAR(2) COMMENT 'Act/Int: Amusement Park Visitors',
  act_int_arts_and_crafts VARCHAR(2) COMMENT 'Act/Int: Arts and Crafts',
  act_int_attend_order_educational_programs VARCHAR(2) COMMENT 'Act/Int: Attend/Order Educational Programs',
  act_int_audio_book_listener VARCHAR(2) COMMENT 'Act/Int: Audio Book Listener',
  act_int_avid_runners VARCHAR(2) COMMENT 'Act/Int: Avid Runners',
  act_int_boating VARCHAR(2) COMMENT 'Act/Int: Boating',
  act_int_book_reader VARCHAR(2) COMMENT 'Act/Int: Book Reader',
  act_int_canoeing_kayaking VARCHAR(2) COMMENT 'Act/Int: Canoeing/Kayaking',
  act_int_casino_gambling VARCHAR(2) COMMENT 'Act/Int: Casino Gambling',
  act_int_cat_owners VARCHAR(2) COMMENT 'Act/Int: Cat Owners',
  act_int_coffee_connoisseurs VARCHAR(2) COMMENT 'Act/Int: Coffee Connoisseurs',
  act_int_cultural_arts VARCHAR(2) COMMENT 'Act/Int: Cultural Arts',
  act_int_digital_magazine_newspapers_buyers VARCHAR(2) COMMENT 'Act/Int: Digital Magazine/Newspapers Buyers',
  act_int_dog_owners VARCHAR(2) COMMENT 'Act/Int: Dog Owners',
  act_int_do_it_yourselfers VARCHAR,
  act_int_eats_at_family_restaurants VARCHAR(2) COMMENT 'Act/Int: Eats at Family Restaurants',
  act_int_eats_at_fast_food_restaurants VARCHAR(2) COMMENT 'Act/Int: Eats at Fast Food Restaurants',
  act_int_e_book_reader VARCHAR,
  act_int_fishing VARCHAR(2) COMMENT 'Act/Int: Fishing',
  act_int_fitness_enthusiast VARCHAR(2) COMMENT 'Act/Int: Fitness Enthusiast',
  act_int_gourmet_cooking VARCHAR(2) COMMENT 'Act/Int: Gourmet Cooking',
  act_int_healthy_living VARCHAR(2) COMMENT 'Act/Int: Healthy Living',
  act_int_home_improvement_spenders VARCHAR(2) COMMENT 'Act/Int: Home Improvement Spenders',
  act_int_hunting_enthusiasts VARCHAR(2) COMMENT 'Act/Int:  Hunting Enthusiasts',
  act_int_listens_to_80s_music VARCHAR(2) COMMENT 'Act/Int: Listens to 80s Music',
  act_int_listens_to_alternative_music VARCHAR(2) COMMENT 'Act/Int: Listens to Alternative Music',
  act_int_listens_to_christian_music VARCHAR(2) COMMENT 'Act/Int: Listens to Christian Music',
  act_int_listens_to_classical_music VARCHAR(2) COMMENT 'Act/Int: Listens to Classical Music',
  act_int_listens_to_country_music VARCHAR(2) COMMENT 'Act/Int: Listens to Country Music',
  act_int_listens_to_hip_hop_music VARCHAR(2) COMMENT 'Act/Int: Listens to Hip Hop Music',
  act_int_listens_to_jazz_music VARCHAR(2) COMMENT 'Act/Int: Listens to Jazz Music',
  act_int_listens_to_music VARCHAR(2) COMMENT 'Act/Int: Listens to Music',
  act_int_listens_to_oldies_music VARCHAR(2) COMMENT 'Act/Int: Listens to Oldies Music',
  act_int_listens_to_pop_music VARCHAR(2) COMMENT 'Act/Int: Listens to Pop Music',
  act_int_listens_to_rock_music VARCHAR(2) COMMENT 'Act/Int: Listens to Rock Music',
  act_int_music_download VARCHAR(2) COMMENT 'Act/Int: Music Download',
  act_int_music_streaming VARCHAR(2) COMMENT 'Act/Int: Music Streaming',
  act_int_nascar_enthusiast VARCHAR(2) COMMENT 'Act/Int: NASCAR Enthusiast',
  act_int_mlb_enthusiast VARCHAR(2) COMMENT 'Act/Int: MLB Enthusiast',
  act_int_nba_enthusiast VARCHAR(2) COMMENT 'Act/Int: NBA Enthusiast',
  act_int_nfl_enthusiast VARCHAR(2) COMMENT 'Act/Int: NFL Enthusiast',
  act_int_nhl_enthusiast VARCHAR(2) COMMENT 'Act/Int: NHL Enthusiast',
  act_int_outdoor_enthusiast VARCHAR(2) COMMENT 'Act/Int: Outdoor Enthusiast',
  act_int_pet_enthusiast VARCHAR(2) COMMENT 'Act/Int: Pet Enthusiast',
  act_int_pga_tour_enthusiast VARCHAR(2) COMMENT 'Act/Int: PGA Tour Enthusiast',
  act_int_photography VARCHAR(2) COMMENT 'Act/Int: Photography',
  act_int_play_golf VARCHAR(2) COMMENT 'Act/Int: Play Golf',
  act_int_plays_hockey VARCHAR(2) COMMENT 'Act/Int: Plays Hockey',
  act_int_plays_soccer VARCHAR(2) COMMENT 'Act/Int: Plays Soccer',
  act_int_plays_tennis VARCHAR(2) COMMENT 'Act/Int: Plays Tennis',
  act_int_political_viewing_on_tv_conservative VARCHAR,
  act_int_political_viewing_on_tv_liberal VARCHAR,
  act_int_political_viewing_on_tv_liberal_comedy VARCHAR,
  act_int_scrapbooking VARCHAR(2) COMMENT 'Act/Int: Scrapbooking',
  act_int_snow_sports VARCHAR(2) COMMENT 'Act/Int: Snow Sports',
  act_int_sports_enthusiast VARCHAR(2) COMMENT 'Act/Int: Sports Enthusiast',
  act_int_sweepstakes_lottery VARCHAR(2) COMMENT 'Act/Int: Sweepstakes/Lottery',
  act_int_video_gamer VARCHAR(2) COMMENT 'Act/Int: Video Gamer',
  act_int_wine_lovers VARCHAR(2) COMMENT 'Act/Int: Wine Lovers',
  act_int_zoo_visitors VARCHAR(2) COMMENT 'Act/Int: Zoo Visitors',
  act_int_coin VARCHAR(2) COMMENT 'Act/Int: Coin Collector',
  act_int_disney VARCHAR(2) COMMENT 'Act/Int: Disney Park Fan',
  act_int_heavy_travel VARCHAR(2) COMMENT 'Act/Int: Frequent Air Traveler',
  act_int_prints_home VARCHAR(2) COMMENT 'Act/Int: Prints Pics at Home',
  act_int_travel_reward VARCHAR(2) COMMENT 'Act/Int: Travel Rewards',
  act_int_on_a_diet VARCHAR(2) COMMENT 'Act/Int: On a Diet',
  act_int_weight_conscious VARCHAR(2) COMMENT 'Act/Int: Weight Conscious',
  buy_bundle VARCHAR(2) COMMENT 'Buyer: Bundle Phone Internet TV',
  buy_coupon_moms VARCHAR(2) COMMENT 'Buyer: Coupon Moms',
  buyer_coupon_users VARCHAR(2) COMMENT 'Buyer: Coupon Users',
  buy__online_shopper VARCHAR(2) COMMENT 'Buyer: Frequent Online Shopper',
  buyer_high_end_spirit_drinkers VARCHAR,
  act_int_importbeer VARCHAR(2) COMMENT 'Buyer: Imported Beer Enthusiast',
  buyer_laptop_owners VARCHAR(2) COMMENT 'Buyer: Laptop Owners',
  buyer_loyalty_card_user VARCHAR(2) COMMENT 'Buyer: Loyalty Card User',
  buyer_luxury_home_goods_store_shopper VARCHAR(2) COMMENT 'Buyer: Luxury Home Goods Store Shopper',
  buyer_luxury_store_shoppers VARCHAR(2) COMMENT 'Buyer: Luxury Store Shoppers',
  buy_microsoft_office VARCHAR(2) COMMENT 'Buyer: Microsoft Office',
  buyer_non_department_store_makeup_brand_user VARCHAR(2) COMMENT 'Buyer: Non-Prestige Makeup Brand User',
  buy_pre_paid_phone VARCHAR,
  buyer_presence_of_automobile VARCHAR(2) COMMENT 'Buyer: Presence of Automobile',
  buyer_department_store_makeup_user VARCHAR(2) COMMENT 'Buyer: Prestige Makeup User',
  buyer_security_system_owners VARCHAR(2) COMMENT 'Buyer: Security System Owners',
  buyer_supercenter_shoppers VARCHAR(2) COMMENT 'Buyer: Supercenter Shoppers',
  buyer_tablet_owners VARCHAR(2) COMMENT 'Buyer: Tablet Owners',
  buyer_teeth_whitener_ VARCHAR(2) COMMENT 'Buyer: Teeth Whitener',
  buy_walmart_1_3 VARCHAR,
  buy_walmart_4plus VARCHAR(2) COMMENT 'Buyer: Walmart 4+ times month',
  buy_walmart_4_9 VARCHAR,
  buyer_warehouse_club_members VARCHAR(2) COMMENT 'Buyer: Warehouse Club Members',
  buy_wet_dog_food VARCHAR(2) COMMENT 'Buyer: Wet Dog Food',
  buyer_young_adult_clothing_shoppers VARCHAR(2) COMMENT 'Buyer: Young Adult Clothing Shoppers',
  comp_ele_iphone VARCHAR(2) COMMENT 'Comp/Elect: Apple iPhone',
  comp_elect_apple_mac VARCHAR(2) COMMENT 'Comp/Elect: Apple Mac User',
  comp_elect_dell VARCHAR,
  donor_contributes_by_volunteering VARCHAR(2) COMMENT 'Donor: Contributes by Volunteering',
  donor_contributes_to_arts_culture_charities VARCHAR(2) COMMENT 'Donor: Contributes to Arts/Culture Charities',
  donor_contributes_to_charities VARCHAR(2) COMMENT 'Donor: Contributes to Charities',
  donor_contributes_to_education_charities VARCHAR(2) COMMENT 'Donor: Contributes to Education Charities',
  donor_contributes_to_health_charities VARCHAR(2) COMMENT 'Donor: Contributes to Health Charities',
  donor_contributes_to_political_charities VARCHAR(2) COMMENT 'Donor: Contributes to Political Charities',
  donor_contributes_to_private_foundations VARCHAR(2) COMMENT 'Donor: Contributes to Private Foundations',
  financial_corporate_credit_card_user VARCHAR(2) COMMENT 'Financial: Corporate Credit Card User',
  financial_credit_card_user VARCHAR(2) COMMENT 'Financial: Credit Card User',
  financial_debit_card_user VARCHAR(2) COMMENT 'Financial: Debit Card User',
  financial_major_credit_card_user VARCHAR(2) COMMENT 'Financial: Major Credit Card User',
  financial_premium_credit_card_user VARCHAR(2) COMMENT 'Financial: Premium Credit Card User',
  financial_store_credit_card_user VARCHAR(2) COMMENT 'Financial: Store Credit Card User',
  finc_amex_card_user VARCHAR(2) COMMENT 'Financial: Amex Card User',
  finc_amex_visa_user VARCHAR(2) COMMENT 'Financial: Amex, Visa User',
  finc_cc_revolve_min VARCHAR(2) COMMENT 'Financial: CC Revolve Pay Min',
  finc_cctransact_all VARCHAR(2) COMMENT 'Financial: CCTransact Pay Full',
  finc_discover_user VARCHAR(2) COMMENT 'Financial: Discover User',
  finc_heavy_visa_user VARCHAR(2) COMMENT 'Financial: Frequent Visa User',
  finc_mastercard_user VARCHAR(2) COMMENT 'Financial: Mastercard User',
  finc_visa_signature VARCHAR(2) COMMENT 'Financial: Visa Signature User',
  food_freq_family_rest VARCHAR(2) COMMENT 'Food: Frequent Family Restaurant Diner',
  food_freq_fast_food VARCHAR(2) COMMENT 'Food: Frequent Fast Food Diner',
  food_genl_family_rest VARCHAR(2) COMMENT 'Food: General Family Restaurant',
  food_occas_fam_rest VARCHAR(2) COMMENT 'Food: Occasional Family Restaurants',
  food_occas_fast_food VARCHAR(2) COMMENT 'Food: Occasional Fast Food Restaurants',
  hobbies_gardening VARCHAR(2) COMMENT 'Hobbies: Gardening',
  invest_active_investor VARCHAR(2) COMMENT 'Invest: Active Investor',
  invest_brokerage_account_owner VARCHAR(2) COMMENT 'Invest: Brokerage Account Owner',
  invest_have_a_retirement_financial_plan VARCHAR(2) COMMENT 'Invest: Have a Retirement Financial Plan',
  invest_mutual_fund_investor VARCHAR(2) COMMENT 'Invest: Mutual Fund Investor',
  invest_participate_in_online_trading VARCHAR(2) COMMENT 'Invest: Participate in Online Trading',
  inv_invest_high_value VARCHAR,
  inv_invest_mid_value VARCHAR,
  tax_offline_tax_soft VARCHAR(2) COMMENT 'Tax: Offline Tax Software User',
  tax_online_tax_app VARCHAR(2) COMMENT 'Tax: Online Tax App User',
  tax_self_prepared VARCHAR,
  tax_tax_return_prof VARCHAR(2) COMMENT 'Tax: Tax Return Prof Service',
  tax_tax_shelter_user VARCHAR(2) COMMENT 'Tax: Tax Shelter User',
  lifestyle_frequent_flyer_program_member VARCHAR(2) COMMENT 'Lifestyle: Frequent Flyer Program Member',
  lifestyle_have_grandchildren VARCHAR(2) COMMENT 'Lifestyle: Have Grandchildren',
  lifestyle_high_frequency_business_traveler VARCHAR(2) COMMENT 'Lifestyle: High Frequency Business Traveler',
  lifestyle_high_frequency_cruise_enthusiast VARCHAR(2) COMMENT 'Lifestyle: High Frequency Cruise Enthusiast',
  lifestyle_high_frequency_domestic_vacationer VARCHAR(2) COMMENT 'Lifestyle: High Frequency Domestic Vacationer',
  lifestyle_high_frequency_foreign_vacationer VARCHAR(2) COMMENT 'Lifestyle: High Frequency Foreign Vacationer',
  lifestyle_hotel_guest_loyalty_program VARCHAR(2) COMMENT 'Lifestyle: Hotel Guest Loyalty Program',
  travel_disney_fans_frequent VARCHAR(1) COMMENT 'Travel: Disney Fans: Theme Park Stores Frequent',
  filler1075 VARCHAR,
  lifestyle_life_insurance_policy_holders VARCHAR(2) COMMENT 'Lifestyle: Life Insurance Policy Holders',
  lifestyle_medical_insurance_policy_holders VARCHAR(2) COMMENT 'Lifestyle: Medical Insurance Policy Holders',
  lifestyle_medicare_policy_holders VARCHAR(2) COMMENT 'Lifestyle: Medicare Policy Holders',
  lifestyle_military_active VARCHAR(2) COMMENT 'Lifestyle: Military - Active',
  lifestyle_military_inactive VARCHAR(2) COMMENT 'Lifestyle: Military - Inactive',
  memberships_aarp_members VARCHAR(2) COMMENT 'Memberships: AARP Members',
  memberships_union_member VARCHAR(2) COMMENT 'Memberships: Union Member',
  online_active_researcher VARCHAR(2) COMMENT 'Online: Active Researcher',
  online_banking VARCHAR(2) COMMENT 'Online: Banking',
  online_frequent_shopper_ VARCHAR(2) COMMENT 'Online: Frequent Shopper',
  online_general_use_email VARCHAR(2) COMMENT 'Online: General Use, Email',
  online_highly_active_user VARCHAR(2) COMMENT 'Online: Highly Active User',
  online_watch_tv_movies VARCHAR(2) COMMENT 'Online: Watch TV, Movies',
  buyer_propensityaccessories_ VARCHAR(1) COMMENT 'HH Expenditures: Accessories Jewelry Beauty',
  buyer_propensityactv_outdoors_hard_goods_ VARCHAR(1) COMMENT 'HH Expenditures: Active Outdoors Hard Goods',
  buyer_propensityactv_outdoors_soft_goods_ VARCHAR(1) COMMENT 'HH Expenditures: Active Outdoors Soft Goods',
  buyer_propensityapparel VARCHAR(1) COMMENT 'HH Expenditures: Apparel',
  buyer_propensitytools__automotive_ VARCHAR(1) COMMENT 'HH Expenditures: Automotive & Tools',
  buyer_propensitybooks_ VARCHAR(1) COMMENT 'HH Expenditures: Books',
  buyer_propensitybusiness_and_home_office_ VARCHAR(1) COMMENT 'HH Expenditures: Business & Home Office',
  buyer_propensitychildrens_products_ VARCHAR(1) COMMENT 'HH Expenditures: Childrens Products',
  buyer_propensitycoins_and_collectibles_ VARCHAR(1) COMMENT 'HH Expenditures: Collectibles',
  buyer_propensitycomputers_laptop_tablet_ VARCHAR(1) COMMENT 'HH Expenditures: Computers & Software',
  buyer_propensitydiy_ VARCHAR(1) COMMENT 'HH Expenditures: DIY',
  buyer_propensityeducation_early_learning_ VARCHAR(1) COMMENT 'HH Expenditures: Education Early Learning',
  buyer_propensityelectronics__gadgets_ VARCHAR(1) COMMENT 'HH Expenditures: Electronics & Appliances',
  buyer_propensityfinancial_services_ VARCHAR(1) COMMENT 'HH Expenditures: Financial Services',
  buyer_propensityfood_snacks_beverages_ VARCHAR(1) COMMENT 'HH Expenditures: Food Snacks Beverages',
  buyer_propensityfurniture_ VARCHAR(1) COMMENT 'HH Expenditures: Furniture & Mattresses',
  buyer_propensitygeneralmisc_ VARCHAR(1) COMMENT 'HH Expenditures: General Retail & Bargain',
  buyer_propensityhealth_ VARCHAR(1) COMMENT 'HH Expenditures: Health',
  buyer_propensityhobbies__entertainment_ VARCHAR(1) COMMENT 'HH Expenditures: Hobbies & Crafts',
  buyer_propensityhome_decor_ VARCHAR(1) COMMENT 'HH Expenditures: Home Decor',
  buyer_propensityhome_domestics_ VARCHAR(1) COMMENT 'HH Expenditures: Home Domestics',
  buyer_propensityhome_maintenance_improve VARCHAR(1) COMMENT 'HH Expenditures: Home Maintenance/Improvement',
  buyer_propensityhousehold_goods_ VARCHAR(1) COMMENT 'HH Expenditures: Household Goods',
  buyer_propensitykitchen_and_cooking_ VARCHAR(1) COMMENT 'HH Expenditures: Kitchen & Cooking',
  buyer_propensitylawn__garden_ VARCHAR(1) COMMENT 'HH Expenditures: Lawn & Garden',
  buyer_propensityluxury_products_ VARCHAR(1) COMMENT 'HH Expenditures: Luxury Products',
  buyer_propensitymens_apparel_accs_groom VARCHAR(1) COMMENT 'HH Expenditures: Mens Apparel Accessories Grooming',
  buyer_propensityoutdoor_living_ VARCHAR(1) COMMENT 'HH Expenditures: Outdoor Living',
  buyer_propensitypets_and_animals_ VARCHAR(1) COMMENT 'HH Expenditures: Pets',
  filler1118 VARCHAR,
  buyer_propensityscience_and_nature_ VARCHAR(1) COMMENT 'HH Expenditures: Science & Nature Products',
  buyer_propensityseasonal_holiday_prods VARCHAR(1) COMMENT 'HH Expenditures: Seasonal Holiday',
  buyer_propensityshoes_ VARCHAR(1) COMMENT 'HH Expenditures: Shoes',
  buyer_propensitytabletop__dining_ VARCHAR(1) COMMENT 'HH Expenditures: Tabletop & Dining',
  buyer_propensitytoys_ VARCHAR(1) COMMENT 'HH Expenditures: Toys',
  buyer_propensitytravel_ VARCHAR(1) COMMENT 'HH Expenditures: Travel',
  buyer_propensitywomens_apparel_accs_beau VARCHAR(1) COMMENT 'HH Expenditures: Women Apparel Accessories Beauty',
  buyer_propensity_instore_total VARCHAR(1) COMMENT 'HHE In-Store Total',
  buyer_propensityaccessories_instore VARCHAR(1) COMMENT 'HHE In-Store: Accessories Jewelry Beauty',
  buyer_propensityactv_outdoors_hard_goods_instore VARCHAR(1) COMMENT 'HHE In-Store: Active Outdoors Hard Goods',
  buyer_propensityactv_outdoors_soft_goods_instore VARCHAR(1) COMMENT 'HHE In-Store: Active Outdoors Soft Goods',
  buyer_propensityapparel_instore VARCHAR(1) COMMENT 'HHE In-Store: Apparel',
  buyer_propensitytools__automotive_instore VARCHAR(1) COMMENT 'HHE In-Store: Automotive & Tools',
  buyer_propensitybooks_instore VARCHAR(1) COMMENT 'HHE In-Store: Books',
  buyer_propensitybusiness_and_home_office_instore VARCHAR(1) COMMENT 'HHE In-Store: Business & Home Office',
  buyer_propensitychildrens_products_instore VARCHAR(1) COMMENT 'HHE In-Store: Childrens Products',
  buyer_propensitycoins_and_collectibles_instore VARCHAR(1) COMMENT 'HHE In-Store: Collectibles',
  buyer_propensitycomputers_laptop_tablet_instore VARCHAR(1) COMMENT 'HHE In-Store: Computers & Software',
  buyer_propensitydiy_instore VARCHAR(1) COMMENT 'HHE In-Store: DIY',
  buyer_propensityeducation_early_learning_instore VARCHAR(1) COMMENT 'HHE In-Store: Education Early Learning',
  buyer_propensityelectronics__gadgets_instore VARCHAR(1) COMMENT 'HHE In-Store: Electronics & Appliances',
  buyer_propensityfinancial_services_instore VARCHAR(1) COMMENT 'HHE In-Store: Financial Services',
  buyer_propensityfood_snacks_beverages_instore VARCHAR(1) COMMENT 'HHE In-Store: Food Snacks Beverages',
  buyer_propensityfurniture_instore VARCHAR(1) COMMENT 'HHE In-Store: Furniture & Mattresses',
  buyer_propensitygeneralmisc_instore VARCHAR(1) COMMENT 'HHE In-Store: General Retail & Bargain',
  buyer_propensityhealth_instore VARCHAR(1) COMMENT 'HHE In-Store: Health',
  buyer_propensityhobbies__entertainment_instore VARCHAR(1) COMMENT 'HHE In-Store: Hobbies & Crafts',
  buyer_propensityhome_decor_instore VARCHAR(1) COMMENT 'HHE In-Store: Home Decor',
  buyer_propensityhome_domestics_instore VARCHAR(1) COMMENT 'HHE In-Store: Home Domestics',
  buyer_propensityhome_maintenance_improve_instore VARCHAR(1) COMMENT 'HHE In-Store: Home Maintenance/Improvement',
  buyer_propensityhousehold_goods_instore VARCHAR(1) COMMENT 'HHE In-Store: Household Goods',
  buyer_propensitykitchen_and_cooking_instore VARCHAR(1) COMMENT 'HHE In-Store: Kitchen & Cooking',
  buyer_propensitylawn__garden_instore VARCHAR(1) COMMENT 'HHE In-Store: Lawn & Garden',
  buyer_propensityluxury_products_instore VARCHAR(1) COMMENT 'HHE In-Store: Luxury Products',
  buyer_propensitymens_apparel_accs_groom_instore VARCHAR(1) COMMENT 'HHE In-Store: Mens Apparel Accessories Grooming',
  buyer_propensityoutdoor_living_instore VARCHAR(1) COMMENT 'HHE In-Store: Outdoor Living',
  buyer_propensitypets_and_animals_instore VARCHAR(1) COMMENT 'HHE In-Store: Pets',
  filler1156 VARCHAR,
  buyer_propensityscience_and_nature_instore VARCHAR(1) COMMENT 'HHE In-Store: Science & Nature Products',
  buyer_propensityseasonal_holiday_prods_instore VARCHAR(1) COMMENT 'HHE In-Store: Seasonal Holiday',
  buyer_propensityshoes_instore VARCHAR(1) COMMENT 'HHE In-Store: Shoes',
  buyer_propensitytabletop__dining_instore VARCHAR(1) COMMENT 'HHE In-Store: Tabletop & Dining',
  buyer_propensitytoys_instore VARCHAR(1) COMMENT 'HHE In-Store: Toys',
  buyer_propensitytravel_instore VARCHAR(1) COMMENT 'HHE In-Store: Travel',
  buyer_propensitywomens_apparel_accs_beau_instore VARCHAR(1) COMMENT 'HHE In-Store: Women Apparel Accessories Beauty',
  buyer_propensity_online_total VARCHAR(1) COMMENT 'HHE Online Total',
  buyer_propensityaccessories_online VARCHAR(1) COMMENT 'HHE Online: Accessories Jewelry Beauty',
  buyer_propensityactv_outdoors_hard_goods_online VARCHAR(1) COMMENT 'HHE Online: Active Outdoors Hard Goods',
  buyer_propensityactv_outdoors_soft_goods_online VARCHAR(1) COMMENT 'HHE Online: Active Outdoors Soft Goods',
  buyer_propensityapparel_online VARCHAR(1) COMMENT 'HHE Online: Apparel',
  buyer_propensitytools__automotive_online VARCHAR(1) COMMENT 'HHE Online: Automotive & Tools',
  buyer_propensitybooks_online VARCHAR(1) COMMENT 'HHE Online: Books',
  buyer_propensitybusiness_and_home_office_online VARCHAR(1) COMMENT 'HHE Online: Business & Home Office',
  buyer_propensitychildrens_products_online VARCHAR(1) COMMENT 'HHE Online: Childrens Products',
  buyer_propensitycoins_and_collectibles_online VARCHAR(1) COMMENT 'HHE Online: Collectibles',
  buyer_propensitycomputers_laptop_tablet_online VARCHAR(1) COMMENT 'HHE Online: Computers & Software',
  buyer_propensitydiy_online VARCHAR(1) COMMENT 'HHE Online: DIY',
  buyer_propensityeducation_early_learning_online VARCHAR(1) COMMENT 'HHE Online: Education Early Learning',
  buyer_propensityelectronics__gadgets_online VARCHAR(1) COMMENT 'HHE Online: Electronics & Appliances',
  buyer_propensityfinancial_services_online VARCHAR(1) COMMENT 'HHE Online: Financial Services',
  buyer_propensityfood_snacks_beverages_online VARCHAR(1) COMMENT 'HHE Online: Food Snacks Beverages',
  buyer_propensityfurniture_online VARCHAR(1) COMMENT 'HHE Online: Furniture & Mattresses',
  buyer_propensitygeneralmisc_online VARCHAR(1) COMMENT 'HHE Online: General Retail & Bargain',
  buyer_propensityhealth_online VARCHAR(1) COMMENT 'HHE Online: Health',
  buyer_propensityhobbies__entertainment_online VARCHAR(1) COMMENT 'HHE Online: Hobbies & Crafts',
  buyer_propensityhome_decor_online VARCHAR(1) COMMENT 'HHE Online: Home Decor',
  buyer_propensityhome_domestics_online VARCHAR(1) COMMENT 'HHE Online: Home Domestics',
  buyer_propensityhome_maintenance_improve_online VARCHAR(1) COMMENT 'HHE Online: Home Maintenance/Improvement',
  buyer_propensityhousehold_goods_online VARCHAR(1) COMMENT 'HHE Online: Household Goods',
  buyer_propensitykitchen_and_cooking_online VARCHAR(1) COMMENT 'HHE Online: Kitchen & Cooking',
  buyer_propensitylawn__garden_online VARCHAR(1) COMMENT 'HHE Online: Lawn & Garden',
  buyer_propensityluxury_products_online VARCHAR(1) COMMENT 'HHE Online: Luxury Products',
  buyer_propensitymens_apparel_accs_groom_online VARCHAR(1) COMMENT 'HHE Online: Mens Apparel Accessories Grooming',
  buyer_propensityoutdoor_living_online VARCHAR(1) COMMENT 'HHE Online: Outdoor Living',
  buyer_propensitypets_and_animals_online VARCHAR(1) COMMENT 'HHE Online: Pets',
  filler1194 VARCHAR,
  buyer_propensityscience_and_nature_online VARCHAR(1) COMMENT 'HHE Online: Science & Nature Products',
  buyer_propensityseasonal_holiday_prods_online VARCHAR(1) COMMENT 'HHE Online: Seasonal Holiday',
  buyer_propensityshoes_online VARCHAR(1) COMMENT 'HHE Online: Shoes',
  buyer_propensitytabletop__dining_online VARCHAR(1) COMMENT 'HHE Online: Tabletop & Dining',
  buyer_propensitytoys_online VARCHAR(1) COMMENT 'HHE Online: Toys',
  buyer_propensitytravel_online VARCHAR(1) COMMENT 'HHE Online: Travel',
  buyer_propensitywomens_apparel_accs_beau_online VARCHAR(1) COMMENT 'HHE Online: Women Apparel Accessories Beauty',
  con20_grocery_deliver VARCHAR(1) COMMENT 'Cons Behavior: Grocery Delivery',
  rs_cord_cutters_recent VARCHAR(1) COMMENT 'Media: Cord Cutters: Recent',
  rs_cable_tv_highspenders VARCHAR(1) COMMENT 'Media: Cable Broadcast TV High Spend',
  rs_audio_highspenders VARCHAR(1) COMMENT 'Media: Streaming Audio High Spend',
  rs_video_high VARCHAR(1) COMMENT 'Media: Streaming Video High Spend',
  rs_tv_brand_comcast VARCHAR(1) COMMENT 'Media: Cable Broadcast TV Brand Comcast',
  rs_tv_brand_directv VARCHAR(1) COMMENT 'Media: Cable Broadcast TV Brand DIRECTV',
  rs_tv_brand_dish_network VARCHAR(1) COMMENT 'Media: Cable Broadcast TV Brand Dish Network',
  rs_tv_brand_spectrum VARCHAR(1) COMMENT 'Media: Cable Broadcast TV Brand Spectrum',
  rs_tv_brand_xfinity VARCHAR(1) COMMENT 'Media: Cable Broadcast TV Brand Xfinity',
  rs_audio_brand_pandora VARCHAR(1) COMMENT 'Media: Streaming Audio Brand Pandora',
  rs_audio_brand_sirius_xm VARCHAR(1) COMMENT 'Media: Streaming Audio Brand Sirius XM',
  rs_audio_brand_spotify VARCHAR(1) COMMENT 'Media: Streaming Audio Brand Spotify',
  rs_video_brand_hbo VARCHAR(1) COMMENT 'Media: Streaming Video Brand HBO',
  rs_video_brand_hulu VARCHAR(1) COMMENT 'Media: Streaming Video Brand Hulu',
  rs_video_brand_netflix VARCHAR(1) COMMENT 'Media: Streaming Video Brand Netflix',
  rs_video_brand_sling_tv VARCHAR(1) COMMENT 'Media: Streaming Video Brand Sling TV',
  rs_video_brand_vudu VARCHAR(1) COMMENT 'Media: Streaming Video Brand Vudu',
  tv_mov_horror VARCHAR(2) COMMENT 'TV/Moves: Horror Movies',
  tv_mov_tv_how_to VARCHAR(2) COMMENT 'TV/Moves: TV How to Shows',
  tv_mov_adventure_mov VARCHAR(2) COMMENT 'TV/Movies: Adventure Movies',
  tv_mov_collg_basketbl VARCHAR(2) COMMENT 'TV/Movies: College Basketball',
  tv_mov_collg_footbl VARCHAR(2) COMMENT 'TV/Movies: College Football',
  tv_mov_comedy_fan VARCHAR(2) COMMENT 'TV/Movies: Comedy Fan',
  tv_mov_cult_classic VARCHAR(2) COMMENT 'TV/Movies: Cult Classics',
  tv_mov_disc_fastnloud VARCHAR(2) COMMENT 'TV/Movies: Discover History Channel',
  tv_mov_docu_foreign VARCHAR(2) COMMENT 'TV/Movies: Docu/Foreign Movies',
  tv_mov_drama_fan VARCHAR(2) COMMENT 'TV/Movies: Drama Fan',
  tv_mov_drama_movies VARCHAR(2) COMMENT 'TV/Movies: Drama Movies',
  tv_mov_family_films_ VARCHAR(2) COMMENT 'TV/Movies: Family Films',
  tv_mov_female_tv VARCHAR(2) COMMENT 'TV/Movies: Female TV Shows',
  tv_mov_freq_movie VARCHAR(2) COMMENT 'TV/Movies: Frequent Movie Attendee',
  tv_mov_game_shows VARCHAR(2) COMMENT 'TV/Movies: Game Shows',
  tv_mov_grammy_watcher VARCHAR(2) COMMENT 'TV/Movies: Grammy Watcher',
  tv_mov_guy_shows VARCHAR(2) COMMENT 'TV/Movies: Male Focused Shows on TV',
  tv_mov_hbo_watcher VARCHAR(2) COMMENT 'TV/Movies: HBO Watcher',
  tv_mov_movie_opening VARCHAR(2) COMMENT 'TV/Movies: Movie Opening Goer',
  tv_mov_oprah_fan VARCHAR(2) COMMENT 'TV/Movies: Oprah Fan',
  tv_mov_oscars VARCHAR(2) COMMENT 'TV/Movies: Oscars Watcher',
  tv_mov_reality_tv VARCHAR(2) COMMENT 'TV/Movies: Reality TV Shows',
  tv_mov_romantic_com VARCHAR(2) COMMENT 'TV/Movies: Romantic Comedy Movies',
  tv_mov_scifi_movie VARCHAR(2) COMMENT 'TV/Movies: Scifi Movie Buff',
  tv_mov_tennis_on_tv VARCHAR(2) COMMENT 'TV/Movies: Tennis on TV',
  tv_mov_thriller_mov VARCHAR(2) COMMENT 'TV/Movies: Thriller Movie Buff',
  tv_mov_top_chef_tv VARCHAR(2) COMMENT 'TV/Movies: Top Chef TV',
  tv_mov_tv_history VARCHAR(2) COMMENT 'TV/Movies: TV History Genre',
  tv_mov_tv_mov VARCHAR(2) COMMENT 'TV/Movies: TV Movies',
  tv_mov_tv_news VARCHAR(2) COMMENT 'TV/Movies: TV News',
  tv_mov_tv_animation VARCHAR(2) COMMENT 'TV/Movies: TV Animation Genre',
  tv_mov_summer_olym VARCHAR(2) COMMENT 'TV/Movies: Summer Olympics',
  tv_mov_winter_olym VARCHAR(2) COMMENT 'TV/Movies: Winter Olympics',
  tv_mov_oscars_fashin VARCHAR(2) COMMENT 'TV/Movies: Oscars Fashion',
  tv_mov_redbox VARCHAR(2) COMMENT 'TV/Movies: Redbox',
  tv_mov_stream VARCHAR(2) COMMENT 'TV/Movies: Streaming',
  dm_well_being_and_diet_active_wb_management VARCHAR,
  dm_health_and_diet_health_and_image_leader VARCHAR(1) COMMENT 'DM: Health and Diet: Health and Image Leader',
  dm_intrnt_actv_level_scores_internet_activity VARCHAR(1) COMMENT 'DM: INTRNT ACTV LEVEL SCORES: INTERNET ACTIVITY',
  dm_intrnt_actv_level_scores_internet_involvmnt VARCHAR(1) COMMENT 'DM: INTRNT ACTV LEVEL SCORES: INTERNET INVOLVMNT',
  dm_intrnt_actvty_scales_commerce VARCHAR(1) COMMENT 'DM: INTRNT ACTVTY SCALES: COMMERCE',
  dm_intrnt_actvty_scales_instant_gratification VARCHAR(1) COMMENT 'DM: INTRNT ACTVTY SCALES: INSTANT GRATIFICATION',
  dm_intrnt_actvty_scales_news_seeking VARCHAR(1) COMMENT 'DM: INTRNT ACTVTY SCALES: NEWS SEEKING',
  dm_intrnt_actvty_scales_research_info_gather VARCHAR(1) COMMENT 'DM: INTRNT ACTVTY SCALES: RESEARCH INFO GATHER',
  dm_media_involvement_ad_negativity VARCHAR(1) COMMENT 'DM: Media Involvement: Ad Negativity',
  dm_media_involvement_advertising_receptivity_ VARCHAR(1) COMMENT 'DM: Media Involvement: Advertising Receptivity',
  dm_media_involvement_magazine_involvement VARCHAR(1) COMMENT 'DM: Media Involvement: Magazine Involvement',
  dm_media_involvement_newspaper_involvement VARCHAR(1) COMMENT 'DM: Media Involvement: Newspaper Involvement',
  dm_media_involvement_radio_involvement VARCHAR(1) COMMENT 'DM: Media Involvement: Radio Involvement',
  dm_media_involvement_tv_involvement VARCHAR(1) COMMENT 'DM: Media Involvement: TV Involvement',
  dm_mobile_scales_feature_focus VARCHAR(1) COMMENT 'DM: Mobile Scales: Feature Focus',
  dm_mobile_scales_switching_ VARCHAR(1) COMMENT 'DM: Mobile Scales: Switching',
  dm_mobile_scales_traditional_use VARCHAR(1) COMMENT 'DM: Mobile Scales: Traditional Use',
  dm_personal_finance_profile_careful_money_mgr VARCHAR(1) COMMENT 'DM: Personal Finance Profile: Careful Money Mgr',
  dm_personal_finance_profile_investment_leader VARCHAR(1) COMMENT 'DM: Personal Finance Profile: Investment Leader',
  dm_personal_finance_profile_smart_investor VARCHAR(1) COMMENT 'DM: Personal Finance Profile: Smart Investor',
  dm_self_concept_type_l VARCHAR(1) COMMENT 'DM: Self Concept: Type L',
  dm_self_concept_type_m VARCHAR(1) COMMENT 'DM: Self Concept: Type M',
  dm_self_concept_type_p VARCHAR(1) COMMENT 'DM: Self Concept: Type P',
  dm_self_concept_type_s VARCHAR(1) COMMENT 'DM: Self Concept: Type S',
  dm_self_concept_type_t VARCHAR(1) COMMENT 'DM: Self Concept: Type T',
  dm_shopping_behavior_child_influenced_shopper VARCHAR(1) COMMENT 'DM: Shopping Behavior :Child Influenced Shopper',
  dm_shopping_behavior_approval_seeking_ VARCHAR(1) COMMENT 'DM: Shopping Behavior: Approval Seeking',
  dm_shopping_behavior_brand_loyals VARCHAR(1) COMMENT 'DM: Shopping Behavior: Brand Loyals',
  dm_shopping_behavior_impulse_shopper VARCHAR(1) COMMENT 'DM: Shopping Behavior: Impulse Shopper',
  dm_shopping_behavior_informed_consumer VARCHAR(1) COMMENT 'DM: Shopping Behavior: Informed Consumer',
  dm_shopping_behavior_smart_greens_ VARCHAR(1) COMMENT 'DM: Shopping Behavior: Smart Greens',
  dm_views_family_centered VARCHAR(1) COMMENT 'DM: Views: Family Centered',
  dm_views_social_isolationlife_disstsfctn VARCHAR(1) COMMENT 'DM: Views: Social Isolation/Life Disstsfctn',
  dm_views_work_centered_ VARCHAR(1) COMMENT 'DM: Views: Work Centered',
  trx_24m_best_recency DATE COMMENT 'TRX: 24M Best Recency',
  trx_12m_order_frequency VARCHAR(4) COMMENT 'TRX: 12M Order Frequency',
  trx_24m_order_frequency VARCHAR(4) COMMENT 'TRX: 24M Order Frequency',
  trx_12m_order_dollars VARCHAR(4) COMMENT 'TRX: 12M Order Dollars',
  trx_24m_order_dollars VARCHAR(4) COMMENT 'TRX: 24M Order Dollars',
  trx_24m_average_order_dollar VARCHAR(4) COMMENT 'TRX: 24M Average Order Dollar',
  trx_12m_orders_tvradio_promotion VARCHAR(4) COMMENT 'TRX: 12M Orders TV/Radio Promotion',
  trx_24m_orders_tvradio_promotion VARCHAR(4) COMMENT 'TRX: 24M Orders TV/Radio Promotion',
  trx_12m_orders_direct_mail_promotion VARCHAR(4) COMMENT 'TRX: 12M Orders Direct Mail Promotion',
  trx_24m_orders_direct_mail_promotion VARCHAR(4) COMMENT 'TRX: 24M Orders Direct Mail Promotion',
  trx_12m_orders_email_promotion VARCHAR(4) COMMENT 'TRX: 12M Orders Email Promotion',
  trx_24m_orders_email_promotion VARCHAR(4) COMMENT 'TRX: 24M Orders Email Promotion',
  trx_12m_orders_insert_promotion VARCHAR(4) COMMENT 'TRX: 12M Orders Insert Promotion',
  trx_24m_orders_insert_promotion VARCHAR(4) COMMENT 'TRX: 24M Orders Insert Promotion',
  trx_12m_orders_internet_promotion VARCHAR(4) COMMENT 'TRX: 12M Orders Internet Promotion',
  trx_24m_orders_internet_promotion VARCHAR(4) COMMENT 'TRX: 24M Orders Internet Promotion',
  trx_24m_order_recency_code VARCHAR(1) COMMENT 'TRX: 24M Order Recency Code',
  trx_24m_order_frequency_code VARCHAR(1) COMMENT 'TRX: 24M Order Frequency Code',
  trx_24m_order_dollar_code VARCHAR(1) COMMENT 'TRX: 24M Order Dollar Code',
  trx_24m_average_order_dollar_code VARCHAR(1) COMMENT 'TRX: 24M Average Order Dollar Code',
  trx_12m_payment_frequency VARCHAR(4) COMMENT 'TRX: 12M Payment Frequency',
  trx_24m_payment_frequency VARCHAR(4) COMMENT 'TRX: 24M Payment Frequency',
  trx_12m_payment_dollar VARCHAR(4) COMMENT 'TRX: 12M Payment Dollar',
  trx_24m_payment_dollar VARCHAR(4) COMMENT 'TRX: 24M Payment Dollar',
  trx_12m_credit_card_dollar VARCHAR(4) COMMENT 'TRX: 12M Credit Card Dollar',
  trx_24m_credit_card_dollar VARCHAR(4) COMMENT 'TRX: 24M Credit Card Dollar',
  trx_24m_purchase_credit_frequency VARCHAR(4) COMMENT 'TRX: 24M Purchase Credit Frequency',
  trx_24m_purchase_cash_frequency VARCHAR(4) COMMENT 'TRX: 24M Purchase Cash Frequency',
  trx_24m_offline_order_amount_dollar VARCHAR(4) COMMENT 'TRX: 24M Offline Order Amount Dollar',
  trx_24m_offline_order_frequency VARCHAR(4) COMMENT 'TRX: 24M Offline Order Frequency',
  trx_24m_offline_average_order_amount_dollar VARCHAR(4) COMMENT 'TRX: 24M Offline Average Order Amount Dollar',
  trx_24m_online_order_amount_dollar VARCHAR(4) COMMENT 'TRX: 24M Online Order Amount Dollar',
  trx_24m_online_order_frequency VARCHAR(4) COMMENT 'TRX: 24M Online Order Frequency',
  trx_24m_online_average_order_amount_dollar VARCHAR(4) COMMENT 'TRX: 24M Online Average Order Amount Dollar',
  trx_pets_and_animals_recency DATE COMMENT 'TRX: Pets and Animals Recency',
  trx_pets_and_animals_frequency VARCHAR(3) COMMENT 'TRX: Pets and Animals Frequency',
  trx_pets_and_animals_dollar VARCHAR(4) COMMENT 'TRX: Pets and Animals Dollar',
  trx_apparel_recency DATE COMMENT 'TRX: Apparel Recency',
  trx_apparel_frequency VARCHAR(3) COMMENT 'TRX: Apparel Frequency',
  trx_apparel_dollar VARCHAR(4) COMMENT 'TRX: Apparel Dollar',
  trx_business_and_home_office_recency DATE COMMENT 'TRX: Business and Home Office Recency',
  trx_business_and_home_office_frequency VARCHAR(3) COMMENT 'TRX: Business and Home Office Frequency',
  trx_business_and_home_office_dollar VARCHAR(4) COMMENT 'TRX: Business and Home Office Dollar',
  trx_childrens_recency DATE COMMENT 'TRX: Childrens Recency',
  trx_childrens_frequency VARCHAR(3) COMMENT 'TRX: Childrens Frequency',
  trx_childrens_dollar VARCHAR(4) COMMENT 'TRX: Childrens Dollar',
  trx_coins_and_collectibles_recency DATE COMMENT 'TRX: Coins and Collectibles Recency',
  trx_coins_and_collectibles_frequency VARCHAR(3) COMMENT 'TRX: Coins and Collectibles Frequency',
  trx_coins_and_collectibles_dollar VARCHAR(4) COMMENT 'TRX: Coins and Collectibles Dollar',
  trx_cooking_recency DATE COMMENT 'TRX: Cooking Recency',
  trx_cooking_frequency VARCHAR(3) COMMENT 'TRX: Cooking Frequency',
  trx_cooking_dollar VARCHAR(4) COMMENT 'TRX: Cooking Dollar',
  trx_cosmetics_and_beauty_recency DATE COMMENT 'TRX: Cosmetics and Beauty Recency',
  trx_cosmetics_and_beauty_frequency VARCHAR(3) COMMENT 'TRX: Cosmetics and Beauty Frequency',
  trx_cosmetics_and_beauty_dollar VARCHAR(4) COMMENT 'TRX: Cosmetics and Beauty Dollar',
  trx_crafts_recency DATE COMMENT 'TRX: Crafts Recency',
  trx_crafts_frequency VARCHAR(3) COMMENT 'TRX: Crafts Frequency',
  trx_crafts_dollar VARCHAR(4) COMMENT 'TRX: Crafts Dollar',
  trx_education_and_early_learning_recency DATE COMMENT 'TRX: Education and Early Learning Recency',
  trx_education_and_early_learning_frequency VARCHAR(3) COMMENT 'TRX: Education and Early Learning Frequency',
  trx_education_and_early_learning_dollar VARCHAR(4) COMMENT 'TRX: Education and Early Learning Dollar',
  trx_fiction_recency DATE COMMENT 'TRX: Fiction Recency',
  trx_fiction_frequency VARCHAR(3) COMMENT 'TRX: Fiction Frequency',
  trx_fiction_dollar VARCHAR(4) COMMENT 'TRX: Fiction Dollar',
  trx_fitness_and_exercise_recency DATE COMMENT 'TRX: Fitness and Exercise Recency',
  trx_fitness_and_exercise_frequency VARCHAR(3) COMMENT 'TRX: Fitness and Exercise Frequency',
  trx_fitness_and_exercise_dollar VARCHAR(4) COMMENT 'TRX: Fitness and Exercise Dollar',
  trx_food_snacks_beverages_recency DATE COMMENT 'TRX: Food Snacks Beverages Recency',
  trx_food_snacks_beverages_frequency VARCHAR(3) COMMENT 'TRX: Food Snacks Beverages Frequency',
  trx_food_snacks_beverages_dollar VARCHAR(4) COMMENT 'TRX: Food Snacks Beverages Dollar',
  trx_gardening_recency DATE COMMENT 'TRX: Gardening Recency',
  trx_gardening_frequency VARCHAR(3) COMMENT 'TRX: Gardening Frequency',
  trx_gardening_dollar VARCHAR(4) COMMENT 'TRX: Gardening Dollar',
  trx_editorial_and_environmental_recency DATE COMMENT 'TRX: Editorial and Environmental Recency',
  trx_editorial_and_environmental_frequency VARCHAR(3) COMMENT 'TRX: Editorial and Environmental Frequency',
  trx_editorial_and_environmental_dollar VARCHAR(4) COMMENT 'TRX: Editorial and Environmental Dollar',
  trx_health_recency DATE COMMENT 'TRX: Health Recency',
  trx_health_frequency VARCHAR(3) COMMENT 'TRX: Health Frequency',
  trx_health_dollar VARCHAR(4) COMMENT 'TRX: Health Dollar',
  trx_household_goods_recency DATE COMMENT 'TRX: Household Goods Recency',
  trx_household_goods_frequency VARCHAR(3) COMMENT 'TRX: Household Goods Frequency',
  trx_household_goods_dollar VARCHAR(4) COMMENT 'TRX: Household Goods Dollar',
  trx_diy_recency DATE COMMENT 'TRX: DIY Recency',
  trx_diy_frequency VARCHAR(3) COMMENT 'TRX: DIY Frequency',
  trx_diy_dollar VARCHAR(4) COMMENT 'TRX: DIY Dollar',
  trx_hispanicrelated_recency DATE COMMENT 'TRX: Hispanic-Related Recency',
  trx_hispanicrelated_frequency VARCHAR(3) COMMENT 'TRX: Hispanic-Related Frequency',
  trx_hispanicrelated_dollar VARCHAR(4) COMMENT 'TRX: Hispanic-Related Dollar',
  trx_history_recency DATE COMMENT 'TRX: History Recency',
  trx_history_frequency VARCHAR(3) COMMENT 'TRX: History Frequency',
  trx_history_dollar VARCHAR(4) COMMENT 'TRX: History Dollar',
  trx_hobbies_recency DATE COMMENT 'TRX: Hobbies Recency',
  trx_hobbies_frequency VARCHAR(3) COMMENT 'TRX: Hobbies Frequency',
  trx_hobbies_dollar VARCHAR(4) COMMENT 'TRX: Hobbies Dollar',
  trx_holidays_recency DATE COMMENT 'TRX: Holidays Recency',
  trx_holidays_frequency VARCHAR(3) COMMENT 'TRX: Holidays Frequency',
  trx_holidays_dollar VARCHAR(4) COMMENT 'TRX: Holidays Dollar',
  trx_home_decor_recency DATE COMMENT 'TRX: Home Decor Recency',
  trx_home_decor_frequency VARCHAR(3) COMMENT 'TRX: Home Decor Frequency',
  trx_home_decor_dollar VARCHAR(4) COMMENT 'TRX: Home Decor Dollar',
  trx_home_improvement_recency DATE COMMENT 'TRX: Home Improvement Recency',
  trx_home_improvement_frequency VARCHAR(3) COMMENT 'TRX: Home Improvement Frequency',
  trx_home_improvement_dollar VARCHAR(4) COMMENT 'TRX: Home Improvement Dollar',
  trx_jewelry_recency DATE COMMENT 'TRX: Jewelry Recency',
  trx_jewelry_frequency VARCHAR(3) COMMENT 'TRX: Jewelry Frequency',
  trx_jewelry_dollar VARCHAR(4) COMMENT 'TRX: Jewelry Dollar',
  trx_lifestyle_recency DATE COMMENT 'TRX: Lifestyle Recency',
  trx_lifestyle_frequency VARCHAR(3) COMMENT 'TRX: Lifestyle Frequency',
  trx_lifestyle_dollar VARCHAR(4) COMMENT 'TRX: Lifestyle Dollar',
  trx_mens_apparel_accessories_grooming_recency DATE COMMENT 'TRX: Mens Apparel Accessories Grooming Recency',
  trx_mens_apparel_accessories_grooming_frequency VARCHAR(3) COMMENT 'TRX: Mens Apparel Accessories Grooming Frequency',
  trx_mens_apparel_accessories_grooming_dollar VARCHAR(4) COMMENT 'TRX: Mens Apparel Accessories Grooming Dollar',
  trx_money_and_finance_recency DATE COMMENT 'TRX: Money and Finance Recency',
  trx_money_and_finance_frequency VARCHAR(3) COMMENT 'TRX: Money and Finance Frequency',
  trx_money_and_finance_dollar VARCHAR(4) COMMENT 'TRX: Money and Finance Dollar',
  trx_mystery_recency DATE COMMENT 'TRX: Mystery Recency',
  trx_mystery_frequency VARCHAR(3) COMMENT 'TRX: Mystery Frequency',
  trx_mystery_dollar VARCHAR(4) COMMENT 'TRX: Mystery Dollar',
  trx_nutraceuticals_and_supplements_recency DATE COMMENT 'TRX: Nutraceuticals and Supplements Recency',
  trx_nutraceuticals_and_supplements_frequency VARCHAR(3) COMMENT 'TRX: Nutraceuticals and Supplements Frequency',
  trx_nutraceuticals_and_supplements_dollar VARCHAR(4) COMMENT 'TRX: Nutraceuticals and Supplements Dollar',
  trx_politicsrelated_recency DATE COMMENT 'TRX: Politics-Related Recency',
  trx_politicsrelated_frequency VARCHAR(3) COMMENT 'TRX: Politics-Related Frequency',
  trx_politicsrelated_dollar VARCHAR(4) COMMENT 'TRX: Politics-Related Dollar',
  trx_puzzles_games_recency DATE COMMENT 'TRX: Puzzles Games Recency',
  trx_puzzles_games_frequency VARCHAR(3) COMMENT 'TRX: Puzzles Games Frequency',
  trx_puzzles_games_dollar VARCHAR(4) COMMENT 'TRX: Puzzles Games Dollar',
  trx_reference_recency DATE COMMENT 'TRX: Reference Recency',
  trx_reference_frequency VARCHAR(3) COMMENT 'TRX: Reference Frequency',
  trx_reference_dollar VARCHAR(4) COMMENT 'TRX: Reference Dollar',
  filler1420 VARCHAR,
  filler1421 VARCHAR,
  filler1422 VARCHAR,
  trx_romance_recency DATE COMMENT 'TRX: Romance Recency',
  trx_romance_frequency VARCHAR(3) COMMENT 'TRX: Romance Frequency',
  trx_romance_dollar VARCHAR(4) COMMENT 'TRX: Romance Dollar',
  trx_science_and_nature_recency DATE COMMENT 'TRX: Science and Nature Recency',
  trx_science_and_nature_frequency VARCHAR(3) COMMENT 'TRX: Science and Nature Frequency',
  trx_science_and_nature_dollar VARCHAR(4) COMMENT 'TRX: Science and Nature Dollar',
  trx_sports_recency DATE COMMENT 'TRX: Sports Recency',
  trx_sports_frequency VARCHAR(3) COMMENT 'TRX: Sports Frequency',
  trx_sports_dollar VARCHAR(4) COMMENT 'TRX: Sports Dollar',
  trx_vacation_and_travel_recency DATE COMMENT 'TRX: Vacation and Travel Recency',
  trx_vacation_and_travel_frequency VARCHAR(3) COMMENT 'TRX: Vacation and Travel Frequency',
  trx_vacation_and_travel_dollar VARCHAR(4) COMMENT 'TRX: Vacation and Travel Dollar',
  trx_womens_fashion_recency DATE COMMENT 'TRX: Womens Fashion Recency',
  trx_womens_fashion_frequency VARCHAR(3) COMMENT 'TRX: Womens Fashion Frequency',
  trx_womens_fashion_dollar VARCHAR(4) COMMENT 'TRX: Womens Fashion Dollar',
  trx_books_recency DATE COMMENT 'TRX: Books Recency',
  trx_books_frequency VARCHAR(3) COMMENT 'TRX: Books Frequency',
  trx_books_dollar VARCHAR(4) COMMENT 'TRX: Books Dollar',
  c20_cyerpershhforpopinhh VARCHAR(4) COMMENT 'CAPE2020: Density: Pers Per HH for Pop in HH',
  c20_cyeppage0017 VARCHAR(4) COMMENT 'CAPE2020: Age: Pop: % 0-17',
  c20_cyeppagege18 VARCHAR(4) COMMENT 'CAPE2020: Age: Pop: % 18-99+',
  c20_cyeppagege65 VARCHAR(4) COMMENT 'CAPE2020: Age: Pop: % 65-99+',
  c20_cyempage VARCHAR(4) COMMENT 'CAPE2020: Age: Pop: Med Age',
  c20_cyemhuage VARCHAR(2) COMMENT 'CAPE2020: Built: HU: Med Housing Unit Age',
  c20_cyephchldmcplfamch VARCHAR(4) COMMENT 'CAPE2020: ChldHH: % Marr Couple FamW/ Pers LT18',
  c20_cyephchldmcplfamnoch VARCHAR(4) COMMENT 'CAPE2020: ChldHH: % Marr Couple FamW/O Pers LT18',
  c20_cyephchldhhch VARCHAR(4) COMMENT 'CAPE2020: ChldHH: % with Pers LT18',
  c20_cyempp25educattained VARCHAR(4) COMMENT 'CAPE2020: Educ: Pop25+: Med Education Attained',
  c20_cyeppethnasian VARCHAR(4) COMMENT 'CAPE2020: Pop: % Asian Only',
  c20_cyeppethnblack VARCHAR(4) COMMENT 'CAPE2020: Pop: % Black Only',
  c20_cyeppethnhisp VARCHAR(4) COMMENT 'CAPE2020: Pop: % Hispanic',
  c20_cyeppethnwhite VARCHAR(4) COMMENT 'CAPE2020: Pop: % White Only',
  c20_cyeahsize VARCHAR(3) COMMENT 'CAPE2020: HHSize: HH: Average Household Size',
  c20_cyemhuval VARCHAR(7) COMMENT 'CAPE2020: HomVal: OOHU: Med Hm Value',
  c20_cyephustrmobhm VARCHAR(4) COMMENT 'CAPE2020: HUStr: HU: % Mobile Hm',
  c20_cyemfamilyhhincome VARCHAR(6) COMMENT 'CAPE2020: Inc: Med Fam Household Inc',
  c20_cyephlangspan VARCHAR(4) COMMENT 'CAPE2020: LangHH: % Spanish Spking',
  c20_cyepocchuownocc VARCHAR(4) COMMENT 'CAPE2020: Tenancy: OCCHU: % Owner Occupied',
  c20_cyepocchurentocc VARCHAR(4) COMMENT 'CAPE2020: Tenancy: OCCHU: % Renter Occupied',
  c20_cyephmarriedcouplehh VARCHAR(4) COMMENT 'CAPE2020: Typ: HH: % Married Couple Fam',
  c20_cyeispsa VARCHAR(4) COMMENT 'CAPE2020: Educ: ISPSA',
  c20_cyeispsadecile VARCHAR(1) COMMENT 'CAPE2020: Educ: ISPSA Decile',
  c20_cyestatefamincdecile VARCHAR(1) COMMENT 'CAPE2020: Inc: Fam Inc State Decile',
  c20_cyenewlistings VARCHAR(4) COMMENT 'CAPE2020: Move OCCHU: % New Listings',
  c20_cyefshispanic VARCHAR(1) COMMENT 'CAPE2020: Hispanic vs. Non-Hispanic Segment',
  c20_cyefsownrent VARCHAR(1) COMMENT 'CAPE2020: Fam HmOwners vs NonFam Renters Sgmnt',
  c20_cyefsage VARCHAR(1) COMMENT 'CAPE2020: Older vs. Younger Age Segment',
  c20_cyefsaffluence VARCHAR(1) COMMENT 'CAPE2020: High vs. Low Affluence Segment',
  c20_cyefsaframerican VARCHAR(1) COMMENT 'CAPE2020: AfricanAmer vs NonAfricanAmer Segmnt',
  c20_cyefswageeaner VARCHAR(1) COMMENT 'CAPE2020: Empld WageEarners vs OtherInc Segment',
  c20_cyefsstudent VARCHAR(1) COMMENT 'CAPE2020: College Stdt Areas vs NonStdt Areas Seg',
  c20_cyefshomeage VARCHAR(1) COMMENT 'CAPE2020: Older vs. Newer Built Hms Segment',
  c20_cyefvhispanic VARCHAR(5) COMMENT 'CAPE2020: Hispanic vs. Non-Hispanic Score',
  c20_cyefvownrent VARCHAR(5) COMMENT 'CAPE2020: Fam Hm Owners vs NonFam Renters Score',
  c20_cyefvage VARCHAR(5) COMMENT 'CAPE2020: Older vs. Younger Age Score',
  c20_cyefvaffluence VARCHAR(5) COMMENT 'CAPE2020: High vs. Low Affluence Score',
  c20_cyefvaframerican VARCHAR(5) COMMENT 'CAPE2020: AfricanAmer vs NonAfrican Amer Score',
  c20_cyefvwageeaner VARCHAR(5) COMMENT 'CAPE2020: Empld WageEarners vs Other Inc Score',
  c20_cyefvstudent VARCHAR(5) COMMENT 'CAPE2020: CollegeStdt Areas vs NonStdt Areas Scor',
  c20_cyefvhomeage VARCHAR(5) COMMENT 'CAPE2020: Older vs. Newer Built Hms Score',
  fin_fla_networth VARCHAR(1) COMMENT 'Fin: Net Worth'
);